# config/constants.py
# ─── Domain data: specialty lists, emergency keywords ───

PEDIATRIC_SPECIALTIES_EN = [
    "General Pediatrics", "Pediatrics", "Pediatric Cardiology",
    "Pediatric Endocrinology", "Pediatric Neurology", "Pediatric Orthopedics",
    "Pediatric Surgery", "Pedodontic", "Pediatric Allergy & Immunology",
    "Pediatric Nephrology", "Pediatric Hematology", "NICU",
]

PEDIATRIC_SPECIALTIES_AR = [
    "طب الأطفال", "طب الأطفال العام", "القلب والأوعية الدموية للأطفال",
    "أمراض الغدد الصماء للأطفال", "طب أعصاب الأطفال", "جراحة العظام للأطفال",
    "جراحة الأطفال", "طب أسنان الأطفال", "وحدة العناية المركزة لحديثي الولادة",
]

SPECIALTIES_EN = [
    "Activities", "Allergy & Immunology", "Andrology", "Anesthesiology",
    "Arthroplasty", "Audiological medicine", "Bariatric Surgery", "Breast Imaging",
    "Breast Surgery", "Cardiac surgery", "Cardiology", "Cardiothoracic Surgery",
    "Chest", "Cosmetology", "Dental Services", "Dermatology and Cosmatology",
    "E.N.T.", "ENT Head & Neck Surgery", "Emergency", "Endocrinology", "Endodontic",
    "Family Medicine", "General Pediatrics", "General Surgery",
    "General Surgery and Bariatric", "Hematology", "Hernia Surgery", "IVF",
    "Internal Medicine", "Interventional Cardiology", "Interventional Neurology",
    "Interventional Radiology", "Laboratory", "Maxillofacial Surgery",
    "Medical Oncology", "Nephrology", "Neuro Surgery", "Neurology",
    "Neuropsychiatry", "Nutrition", "OBE & GYN", "Oncology", "Ophthalmology",
    "Oral Surgery", "Orthodontic", "Orthopedics", "Otorhinolaryngology",
    "Pediatric Cardiology", "Pediatric Endocrinology", "Pediatric Neurology",
    "Pediatric Orthopedics", "Pediatric Surgery", "Pediatrics", "Pedodontic",
    "Physiotherapy", "Plastic Surgery", "Procedure Room", "Prosthesis",
    "Psychiatry", "Radiology", "Rheumatology", "Screening", "Spine Surgery",
    "Surgical Oncology", "Urology", "Urology and Andrology", "Vascular Surgery",
]

SPECIALTIES_AR = [
    "أمراض الجهاز الهضمي", "أمراض الدم", "أمراض الذكورة", "أمراض الروماتيزم",
    "أمراض الصدرية", "أمراض الغدد الصماء للأطفال", "أمراض القلب التدخلية",
    "أمراض النساء والتوليد", "أنشطة", "أنف وأذن وحنجرة", "الأشعة",
    "الأشعة التداخلية", "الأمراض الجلدية", "الأنف والأذن والحنجرة",
    "الأورام الطبية", "الأورام النسائية", "التجميل", "التخدير", "الجراحة العامة",
    "الحساسية والمناعة", "السمعيات", "الصدر", "الطب الباطني", "الطب النفسي",
    "العلاج الطبيعي", "الغدد الصماء", "الفحص المبدئي", "القلب والأوعية الدموية",
    "القلب والأوعية الدموية للأطفال", "المخ و الأعصاب", "المختبر",
    "تركيبات الأسنان", "تصوير الثدي", "تغذية", "تقويم الأسنان", "جراحات السمنة",
    "جراحة استبدال المفاصل", "جراحة الأطفال", "جراحة الأوعية الدموية",
    "جراحة التجميل", "جراحة الثدي", "جراحة الرأس والرقبة (أنف وأذن وحنجرة)",
    "جراحة الشرج والقولون", "جراحة العظام", "جراحة العظام للأطفال",
    "جراحة العمود الفقري", "جراحة الفتق", "جراحة القدم والكاحل", "جراحة القلب",
    "جراحة القلب والصدر", "جراحة المخ و الأعصاب", "جراحة المسالك البولية",
    "جراحة الوجه والفكين", "جراحة اليد", "خدمات الأسنان", "طب أسنان الأطفال",
    "طب أعصاب الأطفال", "طب الأسرة", "طب الأطفال", "طب الأطفال العام",
    "طب الأم والجنين", "طب الأنف والأذن والحنجرة", "طب الاسرة", "طب العيون",
    "طب النفس والأعصاب", "طوارئ", "علاج الأعصاب التداخلي", "علاج العقم و تأخر الحمل",
    "علاج تحفظي", "علاج جذور الأسنان", "علم الأعصاب التدخلي", "علم الأورام",
    "غرفة الإجراءات الطبية", "مناظير الركبة والكتف",
    "وحدة العناية المركزة لحديثي الولادة",
]

EMERGENCY_KEYWORDS = [
    "chest pain", "severe chest pain", "heavy bleeding", "unconscious",
    "can't breathe", "cannot breathe", "stroke", "heart attack",
    "not breathing", "severe bleeding", "fainted", "seizure",
    "loss of consciousness", "difficulty breathing", "choking",
    "severe headache", "sudden vision loss", "paralysis",
    "ألم شديد في الصدر", "نزيف حاد", "فقدان الوعي", "لا يتنفس",
    "سكتة دماغية", "نوبة قلبية", "تشنجات", "إغماء",
]

# ── Insurance companies accepted at Andalusia ──
# Used for fuzzy matching when patient mentions their insurance
INSURANCE_COMPANIES = [
    "Bupa", "بوبا", "بوبه", "بوپا",
    "Tawuniya", "التعاونية", "تعاونية", "التعاونيه",
    "Medgulf", "ميدغلف",
    "MedRight", "ميدرايت", "مدرايت", "ميد رايت",
    "Malath", "ملاذ",
    "GIG", "جي اي جي",
    "AXA", "اكسا",
    "Walaa", "ولاء",
    "Al Rajhi Takaful", "الراجحي تكافل",
    "Allianz", "اليانز",
    "MetLife", "ميت لايف",
    "SAICO", "سايكو",
    "Gulf Union", "الخليج المتحدة",
    "Solidarity", "سوليدرتي",
    "Arabian Shield", "الدرع العربي",
    "UCA", "المتحدة للتأمين",
    "Amana", "أمانة",
    "Salama", "سلامة",
    "Al Ahlia", "الأهلية",
    "Enaya", "عناية",
    "Globemed", "جلوبال ميد",
    "NextCare", "نكست كير",
    "NAS", "ناس",
    "Misr Insurance", "مصر للتأمين",
    "Egyptian Life", "المصرية للتأمين",
    "Alico", "أليكو",
    "Mohimmatkom", "مهمتكم",
]

# ── EN → AR specialty display names (for showing to Arabic patients) ──
# This is a MANUAL mapping — the SPECIALTIES_EN and SPECIALTIES_AR lists
# are different lengths and independently sorted, so zip() doesn't work.
SPECIALTY_EN_TO_AR = {
    "Allergy & Immunology": "الحساسية والمناعة",
    "Andrology": "أمراض الذكورة",
    "Anesthesiology": "التخدير",
    "Audiological medicine": "السمعيات",
    "Bariatric Surgery": "جراحات السمنة",
    "Breast Surgery": "جراحة الثدي",
    "Cardiac surgery": "جراحة القلب",
    "Cardiology": "القلب والأوعية الدموية",
    "Cardiothoracic Surgery": "جراحة القلب والصدر",
    "Chest": "الصدر",
    "Cosmetology": "التجميل",
    "Dental Services": "خدمات الأسنان",
    "Dermatology and Cosmatology": "الأمراض الجلدية",
    "E.N.T.": "أنف وأذن وحنجرة",
    "ENT Head & Neck Surgery": "جراحة الرأس والرقبة",
    "Emergency": "طوارئ",
    "Endocrinology": "الغدد الصماء",
    "Endodontic": "علاج جذور الأسنان",
    "Family Medicine": "طب الأسرة",
    "General Pediatrics": "طب الأطفال العام",
    "General Surgery": "الجراحة العامة",
    "General Surgery and Bariatric": "الجراحة العامة وجراحات السمنة",
    "Hematology": "أمراض الدم",
    "Hernia Surgery": "جراحة الفتق",
    "IVF": "علاج العقم وتأخر الحمل",
    "Internal Medicine": "الطب الباطني",
    "Interventional Cardiology": "أمراض القلب التدخلية",
    "Interventional Neurology": "علاج الأعصاب التداخلي",
    "Maxillofacial Surgery": "جراحة الوجه والفكين",
    "Medical Oncology": "الأورام الطبية",
    "Nephrology": "الكلى",
    "Neuro Surgery": "جراحة المخ والأعصاب",
    "Neurology": "المخ والأعصاب",
    "Neuropsychiatry": "طب النفس والأعصاب",
    "Nutrition": "تغذية",
    "OBE & GYN": "أمراض النساء والتوليد",
    "Oncology": "علم الأورام",
    "Ophthalmology": "طب العيون",
    "Oral Surgery": "جراحة الفم",
    "Orthodontic": "تقويم الأسنان",
    "Orthopedics": "جراحة العظام",
    "Otorhinolaryngology": "أنف وأذن وحنجرة",
    "Pediatric Cardiology": "القلب والأوعية الدموية للأطفال",
    "Pediatric Endocrinology": "أمراض الغدد الصماء للأطفال",
    "Pediatric Neurology": "طب أعصاب الأطفال",
    "Pediatric Orthopedics": "جراحة العظام للأطفال",
    "Pediatric Surgery": "جراحة الأطفال",
    "Pediatrics": "طب الأطفال",
    "Pedodontic": "طب أسنان الأطفال",
    "Physiotherapy": "العلاج الطبيعي",
    "Plastic Surgery": "جراحة التجميل",
    "Prosthesis": "تركيبات الأسنان",
    "Psychiatry": "الطب النفسي",
    "Rheumatology": "أمراض الروماتيزم",
    "Spine Surgery": "جراحة العمود الفقري",
    "Surgical Oncology": "الأورام الجراحية",
    "Urology": "جراحة المسالك البولية",
    "Urology and Andrology": "المسالك البولية والذكورة",
    "Vascular Surgery": "جراحة الأوعية الدموية",
}
